description: Sets up the repository by installing Node.js and dependencies for CI jobs

name: Prepare

runs:
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
      shell: bash
  using: composite
